// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Contest Tracker",
    platforms: [
        .iOS("17.6")
    ],
    products: [
        .iOSApplication(
            name: "Contest Tracker",
            targets: ["AppModule"],
            displayVersion: "0.3",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .note),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .calendars(purposeString: "Necesitamos acceso a tu calendario para poder sincronizar tus eventos con el calendario"),
                .reminders(purposeString: "Contest Tracker necesita acceso a Recordatorios para crear y actualizar avisos de fechas importantes de tus concursos.")
            ],
            appCategory: .music
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
